apiVersion: v1
kind: Secret
metadata:
  name: farsight-secrets
  namespace: farsight
  labels:
    app.kubernetes.io/name: farsight
type: Opaque
stringData:
  RIOT_API_KEY: ""
  POSTGRES_USER: "loluser"
  POSTGRES_PASSWORD: "lolpassword"
  FLOWER_USER: "admin"
  FLOWER_PASSWORD: "admin"
