apiVersion: v1
kind: Secret
metadata:
  name: farsight-secrets
  namespace: farsight
  labels:
    app.kubernetes.io/name: farsight
type: Opaque
stringData:
  RIOT_API_KEY: "RGAPI-926f5e9d-01c8-41d4-b40d-2a1f9488d5fc"
  POSTGRES_USER: "loluser"
  POSTGRES_PASSWORD: "lolpassword"
  FLOWER_USER: "admin"
  FLOWER_PASSWORD: "admin"
