"""add_failed_ingestions_table

Revision ID: 289dca6fb1d5
Revises: ddd8106cc210
Create Date: 2026-04-23 00:47:11.165362

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '289dca6fb1d5'
down_revision: Union[str, Sequence[str], None] = 'ddd8106cc210'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('failed_ingestions',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('match_id', sa.String(length=32), nullable=False),
    sa.Column('region', sa.String(length=32), nullable=False),
    sa.Column('error_type', sa.String(length=128), nullable=False),
    sa.Column('error_message', sa.String(length=1024), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('failed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_failed_ingestions_match_id'), 'failed_ingestions', ['match_id'], unique=False)
    op.drop_index(op.f('match_timeline_frames_frame_timestamp_idx'), table_name='match_timeline_frames')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('match_timeline_frames_frame_timestamp_idx'), 'match_timeline_frames', [sa.literal_column('frame_timestamp DESC')], unique=False)
    op.drop_index(op.f('ix_failed_ingestions_match_id'), table_name='failed_ingestions')
    op.drop_table('failed_ingestions')
    # ### end Alembic commands ###
