"""initial_schema

Revision ID: a06cd575f79c
Revises: 
Create Date: 2026-04-18 20:48:39.011126

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a06cd575f79c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('matches',
    sa.Column('gameId', sa.BigInteger(), nullable=False),
    sa.Column('gameDuration', sa.Integer(), nullable=False),
    sa.Column('gameStartTimestamp', sa.BigInteger(), nullable=False),
    sa.Column('queueId', sa.Integer(), nullable=False),
    sa.Column('gameVersion', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('gameId')
    )
    op.create_table('summoners',
    sa.Column('puuid', sa.String(length=78), nullable=False),
    sa.Column('id', sa.String(length=128), nullable=True),
    sa.Column('profileIconId', sa.Integer(), nullable=False),
    sa.Column('summonerLevel', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('puuid')
    )
    op.create_table('match_participants',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('gameId', sa.BigInteger(), nullable=False),
    sa.Column('kills', sa.Integer(), nullable=False),
    sa.Column('deaths', sa.Integer(), nullable=False),
    sa.Column('assists', sa.Integer(), nullable=False),
    sa.Column('totalDamageDealtToChampions', sa.Integer(), nullable=False),
    sa.Column('goldEarned', sa.Integer(), nullable=False),
    sa.Column('visionScore', sa.Integer(), nullable=False),
    sa.Column('championId', sa.Integer(), nullable=False),
    sa.Column('teamId', sa.Integer(), nullable=False),
    sa.Column('individualPosition', sa.String(length=32), nullable=False),
    sa.Column('win', sa.Boolean(), nullable=False),
    sa.Column('challenges', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('perks', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['gameId'], ['matches.gameId'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_match_participants_gameId'), 'match_participants', ['gameId'], unique=False)
    op.create_table('match_timeline_frames',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('match_id', sa.BigInteger(), nullable=False),
    sa.Column('participant_id', sa.Integer(), nullable=False),
    sa.Column('minute', sa.Integer(), nullable=False),
    sa.Column('current_gold', sa.Integer(), nullable=False),
    sa.Column('total_gold', sa.Integer(), nullable=False),
    sa.Column('xp', sa.Integer(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('minions_killed', sa.Integer(), nullable=False),
    sa.Column('jungle_minions_killed', sa.Integer(), nullable=False),
    sa.Column('position_x', sa.Integer(), nullable=False),
    sa.Column('position_y', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['matches.gameId'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    info={'timescaledb_hypertable': True}
    )
    op.create_index('ix_match_timeline_frames_match_id_participant_id_minute', 'match_timeline_frames', ['match_id', 'participant_id', 'minute'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_match_timeline_frames_match_id_participant_id_minute', table_name='match_timeline_frames')
    op.drop_table('match_timeline_frames')
    op.drop_index(op.f('ix_match_participants_gameId'), table_name='match_participants')
    op.drop_table('match_participants')
    op.drop_table('summoners')
    op.drop_table('matches')
    # ### end Alembic commands ###
