"""add_region_to_summoners

Revision ID: ddd8106cc210
Revises: a03c957235b9
Create Date: 2026-04-22 18:48:57.692202

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ddd8106cc210'
down_revision: Union[str, Sequence[str], None] = 'a03c957235b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade():
    # 1. Add column as nullable
    op.add_column(
        "summoners",
        sa.Column("region", sa.String(length=32), nullable=True),
    )

    # 2. Backfill existing rows
    op.execute("UPDATE summoners SET region = 'unknown'")  # or whatever default makes sense

    # 3. Make it NOT NULL
    op.alter_column("summoners", "region", nullable=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('summoners', 'region')
    op.create_index(op.f('match_timeline_frames_frame_timestamp_idx'), 'match_timeline_frames', [sa.literal_column('frame_timestamp DESC')], unique=False)
    # ### end Alembic commands ###
