apiVersion: v1
kind: ConfigMap
metadata:
  name: farsight-config
  namespace: farsight
  labels:
    app.kubernetes.io/name: farsight
data:
  ENVIRONMENT: "development"
  DEBUG: "false"
  API_V1_PREFIX: "/api/v1"
  FRONTEND_ORIGIN: "http://localhost:3000"
  RIOT_REGION: "europe"
  RIOT_PLATFORM: "euw1"
  DATABASE_URL: "postgresql+asyncpg://loluser:lolpassword@postgres:5432/loldb"
  REDIS_URL: "redis://redis:6379/0"
  NEXT_PUBLIC_API_URL: "http://localhost:8000"
