apiVersion: batch/v1
kind: Job
metadata:
  name: migrate
  namespace: farsight
  labels:
    app.kubernetes.io/name: migrate
    app.kubernetes.io/part-of: farsight
spec:
  backoffLimit: 3
  template:
    metadata:
      labels:
        app.kubernetes.io/name: migrate
        app.kubernetes.io/part-of: farsight
    spec:
      enableServiceLinks: false
      restartPolicy: OnFailure
      containers:
        - name: migrate
          image: lol_backend:dev
          imagePullPolicy: IfNotPresent
          command:
            - alembic
            - upgrade
            - head
          envFrom:
            - configMapRef:
                name: farsight-config
            - secretRef:
                name: farsight-secrets
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
